/**
 * components/MeetingSummary.jsx — AI-generated summary shown when call ends.
 *
 * When the host ends the call:
 *   1. We collect the chat transcript from local state
 *   2. Send it to our backend which calls the Claude API
 *   3. Display the returned summary in this modal
 *
 * The modal uses MUI Dialog — a full-screen overlay component.
 */

import { useState, useEffect } from "react";
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Typography,
  Button,
  Box,
  CircularProgress,
  Divider,
  Chip,
  Stack,
} from "@mui/material";
import AutoAwesomeIcon from "@mui/icons-material/AutoAwesome";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import CheckIcon from "@mui/icons-material/Check";
import api from "../services/api";

const MeetingSummary = ({ open, roomCode, chatLog, duration, onClose }) => {
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");

  /**
   * When the dialog opens, request the AI summary.
   * We only do this once (when open flips from false to true).
   */
  useEffect(() => {
    if (!open || summary) return;
    generateSummary();
  }, [open]);

  const generateSummary = async () => {
    setLoading(true);
    setError("");

    try {
      const { data } = await api.post(`/rooms/${roomCode}/summary`, {
        transcript: chatLog, // backend reads req.body.transcript
        duration,
      });
      setSummary(data.summary);
    } catch (err) {
      setError(
        "Couldn't generate summary. The chat log will still be available.",
      );
      console.error("Summary generation failed:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const formatDuration = (seconds) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}m ${s}s`;
  };

  return (
    <Dialog
      open={open}
      maxWidth="sm"
      fullWidth
      PaperProps={{
        sx: {
          bgcolor: "background.paper",
          border: "1px solid",
          borderColor: "divider",
          borderRadius: 4,
        },
      }}
    >
      <DialogTitle sx={{ pb: 1 }}>
        <Stack direction="row" sx={{ alignItems: "center" }} spacing={1.5}>
          <Box
            sx={{
              width: 36,
              height: 36,
              borderRadius: "10px",
              background: "linear-gradient(135deg, #0D9488, #2DD4BF)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <AutoAwesomeIcon sx={{ fontSize: 18, color: "#fff" }} />
          </Box>
          <Box>
            <Typography variant="h6" fontWeight={700}>
              Meeting Summary
            </Typography>
           <Typography variant="caption" color="text.secondary">
              Generated by Groq AI
            </Typography>
          </Box>
        </Stack>
      </DialogTitle>

       <Divider sx={{ borderColor: "divider" }} />

      <DialogContent sx={{ py: 3 }}>
        {/* Stats row */}
        {duration && (
          <Stack direction="row" spacing={1} mb={3} flexWrap="wrap" gap={1}>
            <Chip
              label={`Duration: ${formatDuration(duration)}`}
              size="small"
              sx={{
                bgcolor: "rgba(124,58,237,0.15)",
                color: "primary.light",
                border: "1px solid rgba(124,58,237,0.3)",
              }}
            />
            <Chip
              label={`${chatLog?.length || 0} chat messages`}
              size="small"
              sx={{
                bgcolor: "rgba(6,182,212,0.15)",
                color: "secondary.light",
                border: "1px solid rgba(6,182,212,0.3)",
              }}
            />
          </Stack>
        )}

        {/* Summary content */}
        {loading ? (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              py: 4,
              gap: 2,
            }}
          >
            <CircularProgress sx={{ color: "primary.main" }} />
            <Typography variant="body2" color="text.secondary">
              Gemini is summarizing your meeting...
            </Typography>
          </Box>
        ) : error ? (
          <Typography color="error.main" variant="body2">
            {error}
          </Typography>
        ) : (
          <Box
            sx={{
              bgcolor: "background.default",
              border: "1px solid",
              borderColor: "divider",
              borderRadius: 2,
              p: 2.5,
              "& p": { mb: 1, lineHeight: 1.7 },
            }}
          >
            {summary.split("\n").map((line, i) => (
              <Typography
                key={i}
                variant="body2"
                sx={{
                  lineHeight: 1.8,
                  color:
                    line.startsWith("•") || line.startsWith("-")
                      ? "text.primary"
                      : "text.secondary",
                  fontWeight: line.startsWith("#") ? 700 : 400,
                  mb: 0.5,
                }}
              >
                {line || "\u00A0" /* non-breaking space for empty lines */}
              </Typography>
            ))}
          </Box>
        )}
      </DialogContent>

      <Divider sx={{ borderColor: "divider" }} />

      <DialogActions sx={{ px: 3, py: 2, gap: 1 }}>
        {summary && (
          <Button
            variant="outlined"
            startIcon={copied ? <CheckIcon /> : <ContentCopyIcon />}
            onClick={handleCopy}
            sx={{
              borderColor: "divider",
              color: copied ? "success.main" : "text.primary",
            }}
          >
            {copied ? "Copied!" : "Copy summary"}
          </Button>
        )}
        <Button variant="contained" onClick={onClose}>
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default MeetingSummary;
